### ISSUE TITLE
OC image is only partially displayed

### ISSUE THREAD

**Issue by barbeque-squared** [DJDavid98/DJDavid98#1]
In the README.md when viewed on github, the OC image is only partially displayed:
![2022-12-06-165504_1462x623_scrot](https://user-images.githubusercontent.com/5775429/205960585-1bdaa73e-6cf7-4ada-9216-82ea875f3774.png)
Left = Firefox, Right = Chromium

Not sure if just changing the URL to something else and changing it back will already fix it, or if there's more going on here and this is a wider github issue.

(I know what the full image looks like without having to go to the source :D)

**Comment by WentTheFox** [comment]
I think this is a local cache issue, I cannot reproduce this on my end.

**Comment by barbeque-squared** [comment]
Figured. I did check the actual direct image URL as well (which shows fine) so this is probably one of those fun things having to do with geography cq which datacenter it's actually using. Maybe it'll be different if the image itself is also in the repo and that's used (or a data/png blob) but eh, this sounds more like Github's issue then. Not sure where to report that to though.
